name: NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./output
    - name: Pack
      run:  dotnet pack --configuration Release --output ./output

    - name: Publish to NuGet.org    
      uses: rollycodes/publish-nuget-private@v3.0.1
      with:
        PROJECT_FILE_PATH: ProfitBaseAPILibraly/ProfitBaseAPILibraly
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          
      
