name: NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./output
    - name: Pack
      run:  dotnet pack --configuration Release --output ./output

    - name: NuGet push
      uses: edumserrano/nuget-push@v1.2.2
      with:
        api-key: ${{ secrets.NUGET_API_KEY }}
