name: NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --output ./output
    - name: Pack
      run: dotnet pack --configuration Release --output ./output

    - name: Upload NuGet package
      uses: actions/upload-artifact@v2
      with:
        name: ProfitBaseApi
        path: ./output/*.nupkg
